// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// Registers explicitly opted-in ui_components Compose factories, then calls
// each activated plugin's bridge-class register() and hands the Activity to
// bridges implementing MobActivityAware. Bridge-owned factories run last.
// Invoked from MainActivity.onCreate as registerAll(this), before
// setContent renders anything.
package io.mob.plugin

import android.app.Activity

object MobPluginBootstrap {
    private val permissionProviders = mutableListOf<MobPermissionProvider>()

    @JvmStatic
    fun registerAll(activity: Activity) {
        io.mob.camera.MobCameraBridge.register()
        handOff(io.mob.camera.MobCameraBridge, activity)
        collectPermissionProvider(io.mob.camera.MobCameraBridge)
        io.mob.scanner.MobScannerBridge.register()
        handOff(io.mob.scanner.MobScannerBridge, activity)
        collectPermissionProvider(io.mob.scanner.MobScannerBridge)
        io.mob.biometric.MobBiometricBridge.register()
        handOff(io.mob.biometric.MobBiometricBridge, activity)
        collectPermissionProvider(io.mob.biometric.MobBiometricBridge)
        io.mob.notify.MobNotifyBridge.register()
        handOff(io.mob.notify.MobNotifyBridge, activity)
        collectPermissionProvider(io.mob.notify.MobNotifyBridge)
        io.mob.ocr.MobOcrBridge.register()
        handOff(io.mob.ocr.MobOcrBridge, activity)
        collectPermissionProvider(io.mob.ocr.MobOcrBridge)
    }

    // Returns the first plugin-supplied Android permission mapping for `cap`,
    // or null if no activated plugin provides this capability. Core
    // MobBridge.request_permission consults this in its `else` branch.
    @JvmStatic
    fun permissionsFor(cap: String): Array<String>? {
        for (provider in permissionProviders) {
            val perms = provider.permissionsFor(cap)
            if (perms != null) return perms
        }
        return null
    }

    // Hands the Activity to a bridge that opts in via MobActivityAware.
    private fun handOff(bridge: Any, activity: Activity) {
        (bridge as? MobActivityAware)?.setActivity(activity)
    }

    // Records a bridge that opts in via MobPermissionProvider so core
    // MobBridge.request_permission can fall through to it for a capability
    // core no longer knows about.
    private fun collectPermissionProvider(bridge: Any) {
        (bridge as? MobPermissionProvider)?.let {
            if (!permissionProviders.contains(it)) permissionProviders.add(it)
        }
    }
}
