defmodule DukaApp.Components do
  @moduledoc """
  Composite-tag registry for the generated Mob components.

  Call `register_all/0` once at boot, from your app's `on_start/0`:

      def on_start do
        DukaApp.Components.register_all()
        Mob.Nav.push(DukaApp.HomeScreen)
      end

  After that, `<Tabs />` resolves as a tag in `~MOB` markup.

  Regenerated by `mix mishka.ui.gen.mob` — edits are overwritten. Pass
  `--no-register` if you would rather own this file yourself.
  """

  @composites [
    {:tabs, DukaApp.Components.Tabs}
  ]

  @doc "Every `{tag, module}` pairing this app registers."
  @spec composites() :: [{atom(), module()}]
  def composites, do: @composites

  @doc "Registers every composite tag with `Mob.Composite`."
  @spec register_all() :: :ok
  def register_all do
    Enum.each(@composites, fn {tag, module} ->
      Mob.Composite.register(tag, {module, :expand})
    end)
  end
end
